### ISSUE TITLE
No longer working since 0.0.71 or 0.0.72

### ISSUE THREAD

**Issue by captaindork** [thkl/homebridge-homematic#111]
When I update my homebridge-homematic to 0.0.71 or 0.0.72 all my homematic-devices are stuck in "Aktualisieren"-state in the Home-App on my iPads and iPhones. Forcing to install 0.0.70 allows for normal operation again. 
What has been changed? How could I troubleshoot this issue?
Any Suggestion?

**Comment by dkrizic** [comment]
Maybe it has to do with https://github.com/nfarina/homebridge/issues/1277

**Comment by michalkolacek** [comment]
I have the problem also , by init it ends with this :
[5/10/2017, 12:12:43 AM] [HomeMatic CCU] XML-RPC server for interface BidCos-RF. is listening on port 9090.
[5/10/2017, 12:12:43 AM] [HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
/usr/local/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/protocol.js:28
        var content = Buffer.alloc(0);
                             ^

TypeError: Buffer.alloc is not a function
    at Object.Protocol.encodeRequest (/usr/local/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/protocol.js:28:30)
    at methodCall (/usr/local/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/client.js:168:35)
    at HomeMaticRPC.connect (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:226:17)
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:147:10
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:277:39)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1524:8)
    at nextTickCallbackWith1Arg (node.js:430:9)
root@raspberrypi:/etc/init.d#

**Comment by captaindork** [comment]
Hi all,

First of all, yes I am using a rpi3 running jessie.
@dkrizic: Thanks. Interesting one, yes I am facing this one as well (only tcp6) but for me this does not prevent homebridge-homematic from working. I have this behavior, yes, but also with homebridge-homematic 0.0.70 which as I explained above is working fine. However my Network is ipv6 ready, so maybe thats why.
 @michalkolacek: Thanks as well, i have Jessie on rpi3 and am using Node in Version 7.10.0. so i would need to downgrade to node 4.8.3 to run the 0.0.71 or 0.0.72? (I tried, but did not get it working as well. I am now back on node 7.10.0 still using homebridge-homematic 0.0.70 which still works)
@thkl: Thanks for looking into this, however for me this should not be closed as in my opinion not solved...

By the way i have more homebridge plugins running besides homebridge-homematic and they still work fine in their latest versions. homebridge-homematic is the only one that I need to downgrade to an older Version, to make it work.

Regards
captaindork

**Comment by thkl** [comment]
The error above only occurs when the version of node is below 4.5.0. 

Anyway I will publish a version soon that will switch back to the old communication protocol if runs into that error.

**Comment by thkl** [comment]
Additional Info: since .71 I've used the new binrpc module which is the root of that error.  Binrpc is much lighter and faster as the old xmlrpc. But it requires a higher node version.

**Comment by captaindork** [comment]
Thanks thkl,
Seems my Issue is different from michal's one, as I understand its terminating?
For me homebridge runs perfectly with no real difference I could recongnize when using 0.0.72 from a console-output point of view. It does not terminate, its running.
Only the Homematic-Devices are no longer working on Apple devices (Stuck in refreshing).
So as I am not really a guru here, if I can support with some commands or logs, let me know.

If there will be a fallback to xmlrpc and that might then solve it for me, so I am looking forward to this release! However if there is something newer/better/faster I would also be interested in troubleshooting why binrpc does not work for me...

Thanks however for a great plugin!!! Using it day by day!

Regards
captaindork

**Comment by thkl** [comment]
Ah ok, u're writing that you have other plugins running with homebridge. The are alive and working well ?

What you can do: switch the homebridge into Debug mode using  DEBUG=*;homebridge -D as starting command. 
Then a large log will appear.  If a Homematic Device is changing any property you will notice that and also the notification post to HomeKit will appear at the console.

**Comment by captaindork** [comment]
Thanks, 
with the DEBUG oprtins set I can see the following:

With 0.0.70
[5/14/2017, 8:37:53 PM] [Homematic CCU2] RPC getValue (00085569XXXXXF:4 STATE) Response false Errors: null
[5/14/2017, 8:37:53 PM] [Homematic CCU2] RPC getValue (00085569XXXXX7:4 STATE) Response false Errors: null

With 0.0.72 (running very slow, as it waits for each device to timeout [5s]...)
[5/14/2017, 8:41:55 PM] [Homematic CCU2] RPC getValue (00085569XXXXXF:4 STATE) Response undefined Errors: Error: timeout
[5/14/2017, 8:42:00 PM] [Homematic CCU2] RPC getValue (00085569XXXXX7:4 STATE) Response undefined Errors: Error: timeout

(I tried to check if I need to activate something on CCU, but am not sure... CCU Firewall allows access to the homebrisge node...)

Regards
captaindork

**Comment by captaindork** [comment]
Further I could see one success with 0.0.72:
[5/14/2017, 8:48:57 PM] [Homematic CCU2] RPC getValue (LEQ09XXXXX:1 STATE) Response false Errors: null

Not sure about the difference of LEQ and the 0008 Devices, ist this HomeMatic vs. HomeMatic IP?
If so, then at least one of both seems to be working, however I use 99% HmIP Devices with Homekit...

Regards
captaindork

**Comment by thkl** [comment]
Yes, LEQ Devices are Homematic Devices and they are running on a different Interface as 008... (HMiP) Devices. 
Seems that the HMiP Interface is not able to use binrpc. 

Ok that's easy to fix.
